### ISSUE TITLE
Come si riportano le misure "REALI" in metri sul template ICA?

### ISSUE THREAD

**Issue by archeoimprese** [archeoimprese/gna_viarch_analisi_pj#11]
I layer del template lavorano in gradi con EPSG4326 (proiettati in 3857 per una visualizzazione migliore). 
Se in una relazione vi sono indicazioni per la georeferenziazione di tipo metrico, (ad esempio: 50 metri NORD a partire dal lato della casa presente a bordo campo; OPPURE: si misura la bolla di spargimento in un campo su una tavola) e poi la si prova a riportare sul Template, le posizioni saranno scorrette a priori.

Da relazione: area di spargimento di 20x20 metri a 50 metri dallo spigolo nord dell'edificio presente a bordo campo

![immagine](https://user-images.githubusercontent.com/67455205/171572512-ae5fad41-416f-4762-a985-238ced89effc.png)

Stesso spargimento RIDISEGNATO in base alle informazioni in relazione su TEMPLATE ICA

![immagine](https://user-images.githubusercontent.com/67455205/171573415-1859f7b2-51ac-4b6a-a0b6-cb550fc7bcc2.png)

CONFRONTO TRA I DUE POLIGONI: IL VERDE E' IL REALE A TERRA mentre il VIOLA è REALE solo in base al TEMPLATE

![immagine](https://user-images.githubusercontent.com/67455205/171573567-cc1c8b75-eac3-4a5f-872c-a811869a0fdd.png)

PRIMA DI RIPORTARE MISURE NEL MOSI SINCERARSI LE MODALITA' DI DIGITALIZZAZIONE

**Comment by archeoimprese** [comment]
Il layer MOSI 4326 viene disegnato con misura 50 metri verso NORD e un quadrato di 50 metri di lato....
![immagine](https://user-images.githubusercontent.com/67455205/171690152-a3ec076d-9c2b-49d0-863d-e111b1a80dde.png)

.... Poi lo misuriamo ed è diventato 35 metri ...

![immagine](https://user-images.githubusercontent.com/67455205/171690514-38421eaa-7cfe-4fbf-995c-a37d7a58da23.png)

Ellissoide delle Misure EPSG7030 già corretto.
![immagine](https://user-images.githubusercontent.com/67455205/171690624-97921d42-a531-468c-a1ae-a17b09110cbd.png)

**Comment by aleopardi** [comment]
Il problema dipende dall'utilizzo nel progetto del SR 3857. Se la configurazione di un ellissoide consente di effettuare misurazioni corrette (ellissoidiche), lo strumento di digitalizzazione avanzata, che lavora con un sistema di coordinate cartesiane, è soggetto agli errori propri del sistema WGS84/Pseudo-mercatore. Il problema non si presenta se utilizzi qualsiasi altro sistema di coordinate piane.

**Comment by francescomarucci** [comment]
gentilissimi,
siamo qui per decidere se la scelta del sistema di riferimento WGS84 è per qualche motivo "migliorabile": abbiamo stabilito che il tool di QGIS della Digitalizzazione avanzata non "sente" la configurazione generale di QGIS sulle misure (ellissoidiche) e quindi nel caso del progetto in Web Mercator sbaglia tutte le distanze; 
ora è da capire se il malfunzionamento di uno strumento in un software debba influenzare una scelta così delicata quale quella del sistema di riferimento: quanti utenti conoscono/usano questo strumento? quanti interventi di scavo vengono forniti esclusivamente con una descrizione come nell'esempio (a tot metri da... largo tot metri, etc...)? 

e soprattutto:
nel caso in cui venga scelto un sistema di riferimento non Web Mercator e a questo punto mi sembra che la scelta possa andare sul 6875 o 6876 (che differenza c'è?), che strumenti hanno gli utenti per convertire da WGS84 (sistema di riferimento della maggior parte delle fonti)?

la RER ha appena adottato il 7791, e fornisce tutte le trasformazioni NTV2 per QGIS (dalla 3.16), ma nel resto d'Italia?

come risolvere il problema delle [fondamentali] basi Web Mercator (osm, bing, etc...) che riproiettate al volo subiscono delle degradazioni grafiche e di scala (sbagliato livello di z) che ne proibiscono l'utilizzo?

cerchiamo di rispondere tutti insieme a questi dubbi, con l'obiettivo di fornire al cittadino uno strumento sempre più valido e facile da usare,
grazie.

**Comment by pyarchinit** [comment]
Abbiamo abbastanza info. Direi di chiudere la Issue ed inviare PEC. Grazie a tutti per la collaborazione.

**Comment by archeoimprese** [comment]
Soluzione: non usare strumenti di digitalizzazione avanzata su QGIS o plugin come QAD o altri che lavorano solo in cartesiano.
PS: verificare gli strumenti di generazione  buffer o simili se tengono in considerazione l'ellissoide.
