### ISSUE TITLE
Layer RCG problema compilazione causa campo bloccato

### ISSUE THREAD

**Issue by Chiiar** [archeoimprese/gna_viarch_analisi_pj#13]
Release 24 maggio 2022. Non riesco a disegnare i poligoni nel layer RCG e nei relativi layer RCG dettaglio copertura e visibilità perché il campo RCGH è bloccato e non potendolo compilare non mi si attiva il pulsante Ok. Come si può risolvere?

**Comment by AngelaInfarinato** [comment]
I campi di dettaglio sono campi "figli", vanno disegnati all'interno del campo "madre" che è quello della ricognizione. Non devi disegnarlo direttamente dal layer RCG dettaglio (visibilità) o copertura, ma sempre dal layer RCG 

![image](https://user-images.githubusercontent.com/106811553/171839944-0906eca8-b06e-4d36-8ddd-c7a213bbd3ca.png)

cliccando sulla matita e poi sullo strumento "aggiungi poligono", dopo averlo disegnato e chiuso  con il tasto destro, si aprirà il modulo che puoi compilare e salvare (cosa che non puoi fare se disegni direttamente dal layer).

**Comment by Chiiar** [comment]
Risolto. Era un problema legato alla versione di Qgis non aggiornata

**Comment by pyarchinit** [comment]
Grazie Angela. C'è un riferimento nella guida? Puoi indicare la pagina e dare per chiusa la Issue?

**Comment by Chiiar** [comment]
Manuale operativo, pagina 17

**Comment by pyarchinit** [comment]
Grazie. Dopo chiudo la Issue.

**Comment by archeoimprese** [comment]
Risolto: Manuale operativo, pagina 17
