### ISSUE TITLE
Scheda MOSI - Campo VRRO: quale distanza va riportata?

### ISSUE THREAD

**Issue by archeoimprese** [archeoimprese/gna_viarch_analisi_pj#2]
Base GIS originale in EPSG3004 e layer digitalizzato 1:1 in 3004: Distanza cartesiana delle strutture dal centro della carreggiata interessata dal passaggio dell'opera 9,9 metri 

![immagine](https://user-images.githubusercontent.com/67455205/170643720-45de0117-a617-4360-8f9f-9f0edff972e3.png)

Base GIS GNA in EPSG3857 con layer riportato nel MOSI Multipolygon 4326 e layer digitalizzato 1:1 in EPSG4326: Distanza cartesiana delle strutture dal centro della carreggiata interessata dal passaggio dell'opera 13.7 metri 
![immagine](https://user-images.githubusercontent.com/67455205/170643860-c8101009-cb57-4b5f-8c1a-ea8a88a83aac.png)

Nel campo VRRO del MOSI che distanza va riportata? 9.9 metri o 13 metri?
![immagine](https://user-images.githubusercontent.com/67455205/170644248-53fde511-0323-4294-9aab-d0748e227601.png)

**Comment by aleopardi** [comment]
L'errore è determinato dall'utilizzo nel progetto QGIS del SR WGS84/Pseudo-Mercatore, valido per il web mapping ma non per altro, non essendo un sistema geodetico in quanto il modello di approssimazione della Terra è una sfera perfetta e non un ellissoide. Per effettuare una corretta misurazione è necessario utilizzare un valido sistema di riferimento geodetico, nel qual caso va fatta una misurazione ellissoidica, o cartografico, nel quale possiamo rilevare la sostanziale concordanza tra misurazione ellissoidica e cartesiana entro un determinato range di misure. A tal proposito, andrebbe rammentato che con DPCM 10/11/2011 il "Sistema di riferimento geodetico nazionale adottato dalle amministrazioni italiane è costituito dalla realizzazione ETRF2000 - all’epoca 2008.0 - del Sistema di riferimento geodetico europeo ETRS89, ottenuta nell’anno 2009 dall’Istituto Geografico Militare". La Direzione Geodetica dell'IGM ha anche rilasciato una nota per il corretto utilizzo dei sistemi geodetici di riferimento all'interno dei software GIS (https://www.igmi.org/++theme++igm/pdf/nuova_nota_EPSG.pdf). Infine, aggiungo che si può ovviare al problema rilevato anche solo impostando nelle proprietà del progetto un ellissoide per il calcolo delle misure, nel qual caso va utilizzato ovviamente il calcolo ellissoidico.

**Comment by Bomby1977** [comment]
A me di default, aprendo il template rilasciato il 23 Maggio, dà come SR EPSG3857, a sto punto perchè non adeguarsi alla nota dell'IGM e impostare di default un sistema indicato nella nota come ETRF89 o ETRF2000 per fare un esempio?

**Comment by francescomarucci** [comment]
come dicevo nella conferenza di oggi, confermo che pur avendo il progetto in 3857, la misura delle distanze (e superfici), scegliendo una trasformazione ellissoidica (con ellissoide scelto nel progetto epsg:7030, che è il default), la misura è corretta.
scegliendo invece un calcolo "cartesiano" la misura è esagerata di una buona percentuale dovuta al fatto che le coordinate web mercator non sono piane metriche.
nel manuale verrà specificata questa configurazione in modo da ridurre eventuali errori di calcolo.
nell'immagine, vi assicuro che il campo di calcio accanto a casa mia è largo 42 metri:
![Senzanome](https://user-images.githubusercontent.com/1571351/171162359-a06ecd19-3a38-49ca-a38c-0f4919d39bbf.png)

**Comment by aleopardi** [comment]
Come precisato in precedenza, è necessario impostare nelle proprietà del progetto un ellissoide per il calcolo delle misure, perché nel progetto rilasciato probabilmente è stata modificata la voce relativa all'ellissoide per il calcolo di aree e misure che, come giustamente osservato, in QGIS di default è il WGS84 (EPSG 7030). Forse è il caso di fare una verifica sul progetto rilasciato.
![Cattura2](https://user-images.githubusercontent.com/10011457/171173238-639aec94-1acb-4ac7-a655-f054f15fdb6e.JPG)

**Comment by francescomarucci** [comment]
verificato: era rimasta una configurazione non corretta nel progetto... grazie tante per la segnalazione!

**Comment by pyarchinit** [comment]
E questo è un altro problema da risolvere:

https://github.com/archeoimprese/gna_viarch_analisi_pj/issues/11

**Comment by archeoimprese** [comment]
> 

Francesco, ma quindi hai sviluppato tu o sviluppi tu il template ICA a livello nazionale? O stai parlando solo di Emilia Romagna? Lo dobbiamo segnalare noi ad ICA nazionale questo problema? Poi abbiamo riscontrato anche il problema della issue #11

**Comment by francescomarucci** [comment]
ciao,
no, il template non l'ho sviluppato io.
io mi sono occupato solamente del geodb+plugin per l'Emilia-Romagna, e del
match verso il template.
ma ciò non toglie che vorrei aiutare a risolvere tutte queste questioni.

probabilmente i tools della digitalizzazione avanzata non tengono conto
della configurazione delle misure. di fatto non funzionano proprio con il
progetto in coordinate geografiche e secondo me non dovrebbero attivarsi
neanche con il 3857.
ad ogni modo non capisco come facciata disegnare con OSM e 3004, che
trasformazione applicate?
domani faccio delle prove e vi so dire.

nel caso questo aspetto diventi critico, che soluzione proponete? pensando
alla scala nazionale...

un saluto,
francesco

Il gio 2 giu 2022, 19:41 Archeoimprese ***@***.***> ha
scritto:

**Comment by aleopardi** [comment]
Credo che una possibile soluzione sia l'utilizzo del sistema cartografico introdotto per il "superamento della discontinuità che caratterizza i fusi tradizionali quando si trattano dati relativi all'intero territorio nazionale" (Italy zone), nel sistema geodetico ufficiale nazionale ETRF2000 all'epoca 2008.0, sebbene tale sistema cartografico sia indicato come più adatto ad una rappresentazione a piccola scala - in questo caso l'errore lineare è più accentuato all'estremità est del territorio nazionale e noteremo una maggiore differenza tra misure cartesiane ed ellissoidiche che credo rientri comunque in un range accettabile per l'ambito di applicazione (es.: a Punta Palascia su una distanza di 50 m avremo una differenza tra misura ellissoidica e cartesiana di circa 10 cm, mentre su una distanza di circa 500 m tale differenza è di circa 1.2 m - a Roma centro è di circa 70 cm). Si può fare riferimento ai codici EPSG della citata nota della Direzione Geodetica dell'IGM [https://www.igmi.org/++theme++igm/pdf/nuova_nota_EPSG.pdf](url)

**Comment by archeoimprese** [comment]
Abbiamo un progetto in 3004 che è l'originale, sotto al quale accendiamo "un WMS qualsiasi", può essere anche la CTR. Fatto sta che nella relazione archeologica del 1995 sta scritto che devo andare 50 metri a nord dall'angolo della casa pincopalla... e quindi, apro la digitalizzazione avanzata e faccio un poligono a 50 metri... vado sul campo e torna tutto.

Apro il template ICA, faccio la stessa operazione e mancano 20 metri all'appello. Risultato? Ho inserito in un DB statale un dato ERRATO che l'ispettore non ha modo di verificare.

In questo momento è possibile che ci siano 500 persone che stanno usando questo metodo di inserimento dati usando in modo automatico il template senza riflettere sulle problematiche GIS che fino al 14 aprile non erano presenti perchè non richieste come competenze.

La soluzione non può partire dai cittadini, ma da chi emana il sistema ovviamente. Però è chiaro che in questo momento il sistema può creare dei blocchi ai lavori che possono avere conseguenze penali e civili (gli ispettori e le Stazioni Appaltanti ci chiedono spesso "a quanti metri possono stare da un'opera"). Strano è che nessuno se ne sia accorto.

**Comment by francescomarucci** [comment]
1.
chi è che mi scrive? sei Luca? perchè aprire una conversazione parallela
quando c'è un canale apposito?

2.
siamo qui per cercare di risolvere problemi non crearne, quindi non accetto
polemiche e critiche che non siano costruttive, se così dovesse continuare
smetto di leggere.

3.
siamo qui per decidere se la scelta del sistema di riferimento WGS84 è per
qualche motivo sbagliata e se ci sono alternative meno sbagliate: abbiamo
stabilito che il tool di QGIS della Digitalizzazione avanzata non "sente"
la configurazione generale di QGIS sulle misure (ellissoidiche) e quindi
nel caso del progetto in Web Mercator sbaglia tutte le distanze; ora è da
capire se il malfunzionamento di uno strumento debba influenzare una scelta
così delicata quale quella del sistema di riferimento: quanti utenti
conoscono/usano questo strumento? quanti interventi di scavo vengono
forniti esclusivamente con una descrizione come nell'esempio (a tot metri
da... largo tot metri, etc...)?

e soprattutto:
nel caso in cui venga scelto un sistema di riferimento non Web Mercator e a
questo punto mi sembra che la scelta possa andare sul 6875 o 6876 (che
differenza c'è?), che strumenti hanno gli utenti per convertire da WGS84
(sistema di riferimento della maggior parte delle fonti)?
la RER ha appena adottato il 7791, e fornisce tutte le trasformazioni NTV2
per QGIS (dalla 3.16), ma nel resto d'Italia?
come risolvere il problema delle [fondamentali] basi Web Mercator (osm,
bing, etc...) che riproiettate al volo subiscono delle degradazioni
grafiche e di scala (sbagliato livello di z) che ne proibiscono l'utilizzo?

cerchiamo di rispondere tutti insieme a questi dubbi, con l'obiettivo di
fornire al cittadino uno strumento valido.
grazie.

un saluto,
francesco

Il giorno ven 3 giu 2022 alle ore 11:09 Archeoimprese <
***@***.***> ha scritto:

**Comment by pyarchinit** [comment]
Il 99% delle relazioni saranno riferimenti generici da misurare su lucido e riportare in modo metrico sul GIS.
Qui non si tratta di GIS, ma di archivistica e di analisi del dato per come lo troviamo negli archivi.

**Comment by pyarchinit** [comment]
Abbiamo abbastanza info. Direi di chiudere la Issue ed inviare PEC. Grazie a tutti per la collaborazione.

**Comment by archeoimprese** [comment]
Soluzione attenzione all'ellissoide impostato nel progtto per le misure.
