### ISSUE TITLE
Campo "LCC-comune" non funzionante in automatico

### ISSUE THREAD

**Issue by lucacherstich** [archeoimprese/gna_viarch_analisi_pj#24]
Sto lavorando con l'ultima release dal sito ICA (1.1 del 24 Maggio 2022).
Disegno un poligono per il MOPR e nella schermata successiva vedo che mentre la regione è presa in automatico il campo "LCC-Comune" non è riconosciuto in automatico.
Il campo non è neanche editabile e, se non è completo, è impossibile andare avanti e salvare il poligono.
Non so se è un problema mio e del mio computer, ma con la precedente release non avevo questo problema.

**Comment by lucacherstich** [comment]
![Problema comune](https://user-images.githubusercontent.com/107541627/173782385-855a96df-ad26-4fd2-abee-d45289e9c8ab.JPG)
Aggiungo questo screenshot per essere più chiaro.
Il manuale operativo spiega come comportarsi in caso di comune errato, ma non mi sembra dica cosa fare in un caso come questo

**Comment by Chiiar** [comment]
Ciao Luca, a me succedeva lo stesso ma ho risolto aggiornando la versione di Qgis (ho aggiornato a quella consigliata 3.22 Biatowieza). Non so se può essere lo stesso problema. Inoltre devi essere certo di avere sotto anche se spenti i comuni della regione su cui stai lavorando nel layer comuni (il filtro per default è impostato sul piemonte se non ricordo male)

**Comment by lucacherstich** [comment]
> Ciao Luca, a me succedeva lo stesso ma ho risolto aggiornando la versione di Qgis (ho aggiornato a quella consigliata 3.22 Biatowieza). Non so se può essere lo stesso problema. Inoltre devi essere certo di avere sotto anche se spenti i comuni della regione su cui stai lavorando nel layer comuni (il filtro per default è impostato sul piemonte se non ricordo male)

Grazie mille! 
Il problema era proprio il filtro sui comuni di cui non mi ero reso conto.
Grazie
