### ISSUE TITLE
Uso di plugin QGIS per ER al posto di Template_GNA: il plugin "non funziona". A chi chiedere? ICA o ER?

### ISSUE THREAD

**Issue by archeoimprese** [archeoimprese/gna_viarch_analisi_pj#27]
In Emilia Romagna per fare una VPIA in centro storico è stata allargata la buffer oltre il necessario per poter schedare quanti più siti per il database (da 50 metri a 150 metri) Emilia Romagna indipendentemente dall'opera da realizzare (una nuova illuminazione di un parco senza sottoservizi).

Per accedere al Database è stato necessario attendere OK della SABAP, una successiva mail per il link da cui scaricare il Plugin per QGIS e successivamente una ulteriore mail per avere le credenziali.

Al momento del download il server della regione risulta INACCESSIBILE.

Domanda: nel DPCM 14 aprile 2022 si fa riferimento al sistema di ICA. Come ci si deve comportare? Chi manda assistenza per la VPIA usando il sistema ER? Sempre ICA?

**Comment by archeoimprese** [comment]
![immagine](https://user-images.githubusercontent.com/67455205/177206702-f83b6336-1737-4ff5-9bf2-76271c240bf8.png)

**Comment by pyarchinit** [comment]
Viene riportato da altri professionisti che il server dopo le 20 non sia raggiungibile.
Come verificare?

**Comment by francescomarucci** [comment]
gentilissimi,
mi permetto di fare due considerazioni:

1.
cerchiamo di essere precisi: qui la regione non c'entra nulla, il plugin ArcheoDB è stato sviluppato dal Segretariato regionale per l'Emilia-Romagna del MiC, quindi non esiste nessun "server della regione";

2.
sapete bene che nel mondo ICT, quando qualcosa non funziona come dovrebbe, la cosa peggiore che un utente può fare è limitarsi a dire "non funziona": quale sistema operativo? quale versione di QGIS? in quali condizioni è stato rilevato l'errore? che messaggio di errore è stato fornito? è stata verificata la connessione ad internet?
sappiamo tutti molto bene che perchè un software sia efficiente è necessaria la collaborazione di tutti, di chi lo fa e di chi lo usa, perchè improvvisamente sembra che ce ne siamo dimenticati e alimentiamo polemiche sterili?


nello specifico: cosa significa che "dopo le 20 [il repository] non è raggiungibile"? è stata fatta la prova in un altro momento?

dal nostro punto di vista possiamo solamente dire che lato server il certificato SSL è stato aggiornato a inizio giugno, è stato accettato in QGIS? se andate nella configurazione di QGIS, per quanto riguarda il server "patrimonioculturale-er.it" trovate questa situazione?

![immagine](https://user-images.githubusercontent.com/1571351/177564174-6d1e75f8-3db5-4d31-9dc3-4c1a61c80903.png)


attendo indicazioni che aiutino a correggere il problema specifico.

saluti,
francesco

**Comment by pyarchinit** [comment]
Altri problemi segnalati relativi alla mancata connessione.
