### ISSUE TITLE
Il poligono MOPR corrisponde alla "buffer" di raccolta dati?

### ISSUE THREAD

**Issue by archeoimprese** [archeoimprese/gna_viarch_analisi_pj#4]
Il layer MOPR corrisponde alla buffer di raccolta dati?

Sembrerebbe così:
Dalla frase iniziale del documento MOPR anche se non si parla esplicitamente di buffer ma di aree contermini.
http://www.ic_archeo.beniculturali.it/getFile.php?id=1375

In caso di affermazione positiva:
- E' stato stabilito in fase preliminare dall'ispettore di zona?
- se deve essere disegnato in metri, come lo si inserisce sul template che ragiona in gradi?

**Comment by pyarchinit** [comment]
Si è la buffer!

**Comment by cinramp** [comment]
Confermo è la buffer. La prima versione del manuale, a pagina 9 dice: "La compilazione parte dal disegno sulla mappa del perimetro della geometria che deve comprendere tutta l’area all’interno della quale è stato effettuato il censimento"

**Comment by archeoimprese** [comment]
SOLUZIONE: durante la diretta ICA per Template ICA + Template ER è stato detto che il MOPR è "l'area vasta" alias la buffer della fase di scoping che devono fare Stazione appaltante e Ispettore per fare la VPIA successivamente.
